### ISSUE TITLE
set taskd's request.limit to 0

### ISSUE THREAD

**Issue by djmitche** [freecinc/freecinc-helm#19]
https://github.com/freecinc/freecinc-issues/issues/9#issuecomment-715410389

**Comment by djmitche** [comment]
@ploth we already see a lot of failures of taskd (one happened just now, in fact).  Is this likely to make that more common?

**Comment by ploth** [comment]
I run my own server since a year after using freecinc for multiple years. thanks! :kissing_heart:
For the migration to my own server I had to set this option. [Further reading.](https://github.com/jackdesert/freecinc/issues/7)
